### ISSUE TITLE
Is the padding module wrong?

### ISSUE THREAD

**Issue by UBCIntelliview** [HRNet/HRFormer#17]
Hello, I observes in the class  PadBlock, the operation you have done is 
"n (qh ph) (qw pw) c -> (ph pw) (n qh qw) c" 
which you makes the padding group as batch dim. Therefore, it may cause a problem that you consider the pad-group wise attention across all batches. Do you think the permutation should be
"n (qh ph) (qw pw) c -> (n ph pw) (qh qw) c"

**Comment by PkuRainBow** [comment]
@LayneH Please help answer the issue.

**Comment by LayneH** [comment]
Hi @UBCIntelliview,

I guess that the operation you pointed out is in [the `LocalPermuteModule`](https://github.com/HRNet/HRFormer/blob/64d7dfcd68152ed3dc415b05a683f59abdabec04/seg/lib/models/backbones/hrt/modules/multihead_isa_attention.py#L406), right?
As for your question, the `forward` function of the `MHA_` class actually takes inputs of shape [tgt_len, bsz, embed_dim] according to [this line](https://github.com/HRNet/HRFormer/blob/64d7dfcd68152ed3dc415b05a683f59abdabec04/seg/lib/models/backbones/hrt/modules/multihead_isa_attention.py#L191). So the implementation should be correct.

**Comment by UBCIntelliview** [comment]
Thank you for your answer.  I think my concern is solved now. Thank you.
